export enum AddFaveProductRequest$SourceModule {
    CART_RECOMMENDED_PRODUCTS = "CART_RECOMMENDED_PRODUCTS",
    HOME_MOST_VIEWED = "HOME_MOST_VIEWED",
    HOME_NEW_PRODUCTS = "HOME_NEW_PRODUCTS",
    HOME_RECENTLY_VIEWED = "HOME_RECENTLY_VIEWED",
    HOME_REORDER = "HOME_REORDER",
    PDP_RECENTLY_VIEWED = "PDP_RECENTLY_VIEWED",
    PDP_SIMILAR_PRODUCTS = "PDP_SIMILAR_PRODUCTS",
}

export enum AddFaveProductRequest$SourcePage {
    CART = "CART",
    HOME = "HOME",
    PDP = "PDP",
    PLP = "PLP",
    REORDER = "REORDER",
}

export enum AddToCartRequest$SourceModule {
    CART_FREEBIE = "CART_FREEBIE",
    CART_RECOMMENDED_PRODUCTS = "CART_RECOMMENDED_PRODUCTS",
    HOME_FAVORITES = "HOME_FAVORITES",
    HOME_MOST_VIEWED = "HOME_MOST_VIEWED",
    HOME_NEW_PRODUCTS = "HOME_NEW_PRODUCTS",
    HOME_RECENTLY_VIEWED = "HOME_RECENTLY_VIEWED",
    HOME_REORDER = "HOME_REORDER",
    PDP_RECENTLY_VIEWED = "PDP_RECENTLY_VIEWED",
    PDP_SIMILAR_PRODUCTS = "PDP_SIMILAR_PRODUCTS",
}

export enum AddToCartRequest$SourcePage {
    CART = "CART",
    FAVORITES = "FAVORITES",
    FREEBIE = "FREEBIE",
    HOME = "HOME",
    PDP = "PDP",
    PLP = "PLP",
    REORDER = "REORDER",
}

export enum BatchAddCartItemRequest$SourceModule {
    ACCOUNT_REORDER = "ACCOUNT_REORDER"
}

export enum BatchAddCartItemRequest$SourcePage {
    ACCOUNT = "ACCOUNT"
}