export default {
    icons:{
        mainTabHome:{
            selected:require("./icons/main_home_sel.png"),
            normal:require("./icons/main_home.png")
        },
        mainTabSearch:{
            selected:require("./icons/main_search_sel.png"),
            normal:require("./icons/main_search.png")
        },
        mainTabRewards:{
            selected:require("./icons/main_reward_sel.png"),
            normal:require("./icons/main_reward.png")
        },
        mainTabFavorites:{
            selected:require("./icons/main_favorite_sel.png"),
            normal:require("./icons/main_favorite.png")
        },
        mainTabAccount:{
            selected:require("./icons/main_tab_account_sel.png"),
            normal:require("./icons/main_tab_account.png")
        },
        navBarShippingCart:require('./icons/home_icon_cart.png'),
        navBarMessage:require('./icons/home_icon_notification.png'),
        navBarFreebie:require('./icons/home_icon_freebies.png'),
        navBarLogo:require('./icons/home_icon_logo.png'),
        navBarHamburger:require('./icons/home_icon_hamburger.png'),
        navBarBack:require('./icons/icon_back.png'),
        mainZipcodeLocation:require("./icons/icon_zipcode_location.png"),
        mainPointsStar:require("./icons/home_icon_star.png"),
        reviewStar:{
            selected:require("./icons/icon_star_sel.png"),
            normal:require("./icons/icon_star.png")
        },
        productCollect:{
            selected:require("./icons/home_icon_collect_sel.png"),
            normal:require("./icons/home_icon_collect.png")
        },
        addToCart:require('./icons/icon_add_to_cart.png'),
        newByList:require('./icons/icon_new_by_list.png'),
        orderStateCheck:require('./icons/home_order_state_check.png'),
        help:{
            call:require('./icons/help_call.png'),
            email:require('./icons/help_email.png'),
            chat:require('./icons/help_chat.png'),
        },
        account:{
            faq:require('./icons/account_faq.png'),
            logOut:require('./icons/account_logout.png'),
            messageSetting:require('./icons/account_notification.png'),
            orderHistory:require('./icons/account_order_history.png'),
            privacyPolicy:require('./icons/account_privacy_policy.png'),
            shippingAddress:require('./icons/account_shipping_address.png'),
            term:require('./icons/account_term.png'),
        },
        navClose:require('./icons/icon_close.png')
    }
}