import {Dimensions, StyleSheet, Platform, NativeModules} from "react-native";
import ScreenUtil from "../util/ScreenUtil";
import StyleUtil from "../util/StyleUtil";

const {width, height} = Dimensions.get("window");
const isIos = Platform.OS === "ios";
const font = "BasisGrotesquePro-Regular";
const fontBlack = "BasisGrotesquePro-Black";
const fontBold = "BasisGrotesquePro-Bold";
const fontLight = "BasisGrotesquePro-Light";
const fontMedium = "BasisGrotesquePro-Medium";
const primaryFont = "CheltenhamEF-Book";

const color = {
    darkBeetroot: "#6F004B",
    beetroot: "#A0006B",
    beetroot20Solid: "#ecd2e3",
    beetroot20: "rgba(160, 0, 107, 0.2)",
    beetroot10: "rgba(173, 0, 116, 0.1)",
    lightBeetRoot: "#F7E5F1",
    pureBlack: "#000",
    black: "#231F20",
    black80: "rgba(35, 31, 32, 0.8)",
    black60: "rgba(35, 31, 32, 0.6)",
    black50: "rgba(35, 31, 32, 0.5)",
    black40: "rgba(35, 31, 32, 0.4)",
    black30: "rgba(35, 31, 32, 0.3)",
    black20: "rgba(35, 31, 32, 0.2)",
    black10: "#E9E9E9",
    warmWhite: "#EFE5E0",
    warmWhite80: "rgba(239, 229, 224, 0.8)",
    warmWhite60: "rgba(239, 229, 224, 0.6)",
    warmWhite70: "rgba(239, 229, 224, 0.7)",
    warmWhite40: "rgba(239, 229, 224, 0.4)",
    warmWhiteUnOpacity: "rgb(250,245,243)",
    warmWhite30: "rgba(239, 229, 224, 0.3)",
    warmWhite20: "rgba(239, 229, 224, 0.2)",
    warmWhite10: "rgba(239, 229, 224, 0.1)",
    brightWhite: "#fff",
    brightWhite80: "rgba(255, 255, 255, 0.8)",
    brightWhite70: "rgba(255, 255, 255, 0.7)",
    brightWhite60: "rgba(255, 255, 255, 0.6)",
    brightWhite40: "rgba(255, 255, 255, 0.4)",
    brightWhite20: "rgba(255, 255, 255, 0.2)",
    brightWhite10: "rgba(255, 255, 255, 0.1)",
    green: "#9EC630",
    green80: "rgba(158, 198, 48, 0.8)",
    green60: "rgba(158, 198, 48, 0.6)",
    green40: "rgba(158, 198, 48, 0.4)",
    green20: "rgba(158, 198, 48, 0.2)",
    green10: "rgba(158, 198, 48, 0.1)",
    yellow: "#FFB533",
    yellow80: "rgba(255, 181, 51, 0.8)",
    yellow60: "rgba(255, 181, 51, 0.6)",
    yellow40: "rgba(255, 181, 51, 0.4)",
    yellow20: "rgba(255, 181, 51, 0.2)",
    yellow10: "rgba(255, 181, 51, 0.1)",
    orange: "#F95C41",
    orange80: "rgba(249, 92, 65, 0.8)",
    orange60: "rgba(249, 92, 65, 0.6)",
    orange40: "rgba(249, 92, 65, 0.4)",
    orange20: "rgba(249, 92, 65, 0.2)",
    orange10: "rgba(249, 92, 65, 0.1)",
    red: "#F14B1D",
    yellowAccent: "#FFA609",
    greenAccent: "#84AD14",
    redAccent: "#F94627",
    pink: "#FC8970",
    shadowColor: "rgba(202, 189, 183, 0.4)",
    borderColor: "#F1E5DF",
    backgroundLight: "#FAFAFA",
    boneColor: "rgb(236,236, 238)",
    boneDarkColor: "rgb(226,226, 228)",
    map: {
        road: "#ffffff",
        administrative: "#f5ede8",
        landscape: "#f5ede8",
        landscapeNatural: "#efe2dc",
        water: "#e7d4cb",
    },
};

const padding = StyleUtil.scale(30);
const IS_BANGSSCREEN = ScreenUtil.isBangsSreen;

export default {
    IS_BANGSSCREEN,
    isIos,
    headerHeight: IS_BANGSSCREEN ? 52 : StyleUtil.scale(68),
    headerPaddingBottom: IS_BANGSSCREEN ? 16 : 0,
    width,
    height,
    sizeDividerNormal: StyleSheet.hairlineWidth,
    imgBaseHeight: StyleUtil.scale(267),
    imgBaseWidth: StyleUtil.scale(315),
    color,
    padding,
    primaryFont,
    font,
    fontLight,
    fontBlack,
    fontBold,
    fontMedium,
    heading1: {
        fontFamily: primaryFont,
        fontSize: StyleUtil.scale(40),
        lineHeight: StyleUtil.scale(44),
        letterSpacing: StyleUtil.scale(-0.5),
        // marginBottom: StyleUtil.scale(16),
        color: color.brightWhite,
    },
    heading2: {
        fontFamily: primaryFont,
        fontSize: StyleUtil.scale(32),
        lineHeight: StyleUtil.scale(36),
        letterSpacing: StyleUtil.scale(0.15),
        color: color.brightWhite,
    },
    heading3: {
        fontFamily: primaryFont,
        fontSize: StyleUtil.scale(24),
        lineHeight: StyleUtil.scale(28),
        letterSpacing: StyleUtil.scale(0.2),
        color: color.black,
    },
    heading4: {
        fontFamily: primaryFont,
        fontSize: StyleUtil.scale(18),
        lineHeight: StyleUtil.scale(24),
        color: color.black,
    },
    title: {
        fontFamily: primaryFont,
        fontSize: StyleUtil.scale(32),
        lineHeight: StyleUtil.scale(36),
        letterSpacing: StyleUtil.scale(0.15),
        color: color.black,
    },
    body1: {
        fontFamily: font,
        fontSize: StyleUtil.scale(16),
        lineHeight: StyleUtil.scale(24),
        letterSpacing: StyleUtil.scale(0.2),
        color: color.black60,
    },
    body2: {
        fontFamily: font,
        fontSize: StyleUtil.scale(14),
        lineHeight: StyleUtil.scale(20),
        letterSpacing: StyleUtil.scale(0.2),
        color: color.black,
    },
    eyebrowPrimary: {
        fontFamily: fontBlack,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(14),
        letterSpacing: StyleUtil.scale(2),
        color: color.black,
    },
    eyebrowPrimaryBold: {
        fontFamily: fontBold,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(12),
        letterSpacing: StyleUtil.scale(2),
        paddingBottom: StyleUtil.scale(2),
        color: color.black,
    },
    eyebrowPrimaryMedium: {
        fontFamily: fontMedium,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(12),
        letterSpacing: StyleUtil.scale(2),
        paddingBottom: StyleUtil.scale(2),
        color: color.black,
    },
    eyebrowSecondary: {
        fontFamily: font,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(14),
        letterSpacing: StyleUtil.scale(2),
        color: color.black60,
    },
    eyebrowSmall: {
        fontFamily: fontBold,
        fontSize: StyleUtil.scale(10),
        lineHeight: StyleUtil.scale(14),
        letterSpacing: StyleUtil.scale(1),
        color: color.black60,
    },
    forms: {
        fontFamily: font,
        fontSize: StyleUtil.scale(18),
        lineHeight: StyleUtil.scale(24),
        letterSpacing: StyleUtil.scale(0.2),
        color: color.black,
    },
    ctasPrimarySecondary: {
        fontFamily: fontBlack,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(14),
        letterSpacing: StyleUtil.scale(2),
        color: color.brightWhite,
    },
    buttonText: {
        fontFamily: fontBold,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(14),
        letterSpacing: StyleUtil.scale(2),
        color: color.brightWhite,
    },
    ctasTertiary: {
        fontFamily: font,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(16),
        letterSpacing: StyleUtil.scale(2),
        color: color.black,
    },
    labels: {
        fontFamily: font,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(16),
        letterSpacing: StyleUtil.scale(0.2),
        color: color.black60,
    },
    legal: {
        color: color.brightWhite70,
        fontFamily: font,
        fontSize: StyleUtil.scale(12),
        lineHeight: StyleUtil.scale(20),
        letterSpacing: StyleUtil.scale(0.2),
    },
    dividerLineStyle: {
        width: width - 2 * padding,
        backgroundColor: color.warmWhite70,
        height: 1,
        marginLeft: padding,
    },
    dividerAllLineStyle: {
        width,
        backgroundColor: color.warmWhite70,
        height: 1,
    },
    dividerLineBoldStyle: {
        width,
        backgroundColor: color.warmWhite70,
        height: 2,
    },
    iconStyles: {
        width: StyleUtil.scale(24),
        height: StyleUtil.scale(24),
    },
    shadowBlack20: {
        shadowColor: color.black20,
        shadowOpacity: 1,
        shadowRadius: 12,
        shadowOffset: {width: 0, height: -4},
        elevation: 12,
    },
    shadow: {
        shadowColor: color.shadowColor,
        shadowOpacity: 1,
        shadowRadius: 20,
        shadowOffset: {width: 0, height: -4},
        elevation: 20,
    },
    shadow52: {
        shadowColor: "rgba(152,134,125,0.5)",
        shadowOpacity: 1,
        shadowRadius: 52,
        shadowOffset: {width: 0, height: 2},
        elevation: 52,
    },
};
