import { HomePageResponseV2$LoggedInData } from "../type/ResponseModels";
import { HomePageRequest } from "../type/RequestModels";
import { ajax } from "../network";

// Attention: This file is generated by "yarn api", do not modify

export class AccountWebService {
    // static listAccountAllergen(request: HomePageRequest): Promise<HomePageResponseV2$LoggedInData> {
    //     return NetworkService.ajax("GET", "/home-page/home-product-v2", {}, null);
    // }
}


// final class HomePageResponseV2$LoggedInData : Codable {
// 	var available_rewards: Double?
// 	var feature_brands: [Brand]?
// 	var last_order: OrderView?
// 	var need_display_points_expiration_warning: Bool
// 	var points_expiration_warning_message: String?
// 	var reward_background_image_url: String?
// 	var static_banners: [Banner]
// 	var top_banners: [Banner]
// 	var top_navs: [TopNav]
// 	var view_all_new_products_action_url: String?

// 	init(available_rewards: Double?,feature_brands: [Brand]?,last_order: OrderView?,need_display_points_expiration_warning: Bool,points_expiration_warning_message: String?,reward_background_image_url: String?,static_banners: [Banner],top_banners: [Banner],top_navs: [TopNav],view_all_new_products_action_url: String?){
// 		self.available_rewards = available_rewards
// 		self.feature_brands = feature_brands
// 		self.last_order = last_order
// 		self.need_display_points_expiration_warning = need_display_points_expiration_warning
// 		self.points_expiration_warning_message = points_expiration_warning_message
// 		self.reward_background_image_url = reward_background_image_url
// 		self.static_banners = static_banners
// 		self.top_banners = top_banners
// 		self.top_navs = top_navs
// 		self.view_all_new_products_action_url = view_all_new_products_action_url
// 	}
// }